### ISSUE TITLE
fix gulp clean

### ISSUE THREAD

**Issue by yuki-takei** [yuki-takei/electron-angular2-boilerplate#4]
```
[02:59:58] Using gulpfile ~/Projects/Calc/calc/gulpfile.js
[02:59:58] Starting 'clean'...
[02:59:58] 'clean' errored after 1.11 ms
[02:59:58] TypeError: Cannot read property '0' of undefined
    at /home/vagrant/Projects/Calc/deps/node_modules/del/node_modules/globby/index.js:18:27
    at Array.forEach (native)
    at sortPatterns (/home/vagrant/Projects/Calc/deps/node_modules/del/node_modules/globby/index.js:17:11)
    at module.exports (/home/vagrant/Projects/Calc/deps/node_modules/del/node_modules/globby/index.js:45:23)
    at module.exports (/home/vagrant/Projects/Calc/deps/node_modules/del/index.js:34:2)
    at Gulp.<anonymous> (/home/vagrant/Projects/Calc/calc/gulp/build.js:127:3)
    at module.exports (/home/vagrant/Projects/Calc/deps/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/vagrant/Projects/Calc/deps/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/vagrant/Projects/Calc/deps/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/vagrant/Projects/Calc/deps/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
```

**Comment by yuki-takei** [comment]
fixed by 3e63a33
